name: Test App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy .env
        run: |
          cp .env.example .env
          pwd
          ls -la
      - name: start sail
        run: |
          ./vendor/bin/sail up -d
      - name: ls in container
        run: |
          ./vendor/bin/sail run ls -la
