name: Test App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: copy .env
        run: cp .env.example .env
      - name: run sail
        run: ./vendor/bin/sail up -d
      - name: generate key
        run: ./vendor/bin/sail artisan key:generate
      - name: migrate db
        run: ./vendor/bin/sail artisan migrate
      - name: execute tests
        run: ./vendor/bin/sail artisan test
